name: modelgenerator
channels:
  - conda-forge
  - esri
  - default
dependencies:
  - arcgis
  - python>=3.7
  - gdal>=2.4
  - pip=21.0
  - ipykernel
  - ipywidgets
  - geopandas>=0.7
  - rasterio
  - imod
  - numpy
  - scipy=1.6.0
  - pandas
  - matplotlib
  - pillow
  - rasterstats>=0.14
  - tqdm
  - netcdf4>=1.5
  - descartes>=1
  - contextily
  - fire
  - jupyter
  - pip:
    - hkvsobekpy==1.5
    - delft3dfmpy==1.2.1
