__title__ = 'tohydamogml'
__description__ = 'Convert DAMO filegdb export to gml'
__version__ = '0.2.8'
__author__ = 'HaskoningDHV'
__author_email__ = ''
__license__ = 'MIT'
__url__ = ''
__keywords__ = 'DAMO HyDAMO GML'